### ISSUE TITLE
Camera not working on any Android device

### ISSUE THREAD

**Issue by mstephano** [ionic-team/photo-gallery-tutorial-ionic4#1]
Hi,

It seams that the camera is not working on any Android devices using Ionic DevApp. Here are the steps to reproduce:
- git clone the repo
- cd into directory and npm i
- start with ionic serve -c
- Using Ionic DevApp for iOS, my iOS devices  are all fine (iPhone5, iPhoneXR and iPad Air2), When clicking on the camera button, I can take picture and submit to the page.
- Using Ionic DevApp for Android, my Android devices don't show the camera (Xiaomi Poco F1 with android 9 MIUI10, Nexus 9 Android 7.1.1) after I click on the camera button, nothing happens:
   - there is no message asking to activate the app permission to use camera
   - I went in the settings manually and activate the camera permission for DevApp and still nothing happens when I click on the camera button

I tried the [AndroidPermission](https://beta.ionicframework.com/docs/native/android-permissions) and still not working.

However, I used the [Platform](https://beta.ionicframework.com/docs/api/platform) (missing from Ionic 4 beta docs, so I used docs from [v3](https://ionicframework.com/docs/api/platform/Platform/)), and none of my Android device return 'cordova' when calling platform.platforms().

Am I missing something? Any help is very appreciated!

Update: I built an apk of my project and debug it on my android devices, and the camera is now fine. The platform 'cordova' is also returned when calling platform.platforms(). Is it possible to fix it for Android Ionic DevApp to work the same as the iOS one? Thank you!

**Comment by gavinheale** [comment]
I have noticed the same problem.  Is there a fix for this yet?

**Comment by dotNetkow** [comment]
Hi there, apologies for the issue. I tested locally - all is well. Looks like DevApp is the issue here.

For the time being, I recommend running a local Android build instead. Follow [these setup instructions](https://beta.ionicframework.com/docs/installation/android), then execute this in a terminal:

ionic cordova run android -l

**Comment by dotNetkow** [comment]
After further investigation, I figured out what is wrong and have [updated the tutorial](https://docs.ionicframework.com/docs/developer-resources/guides/first-app-v4/ios-android-camera). Usually, executing a Cordova build will add a script tag into the index.html file that references Cordova.js. But since we are skipping that step and using DevApp, we have to do it manually ourselves. That's why it's not working for you.

Open up the file at src/index.html and add the following tag into the <head> section:

**<script src="cordova.js"></script>**

Closing. Apologies again - thanks for your patience.
